spring.application.name=ServerProvision

server.port=${SERVER_PORT}
server.address=localhost

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 파일 업로드 설정
spring.servlet.multipart.max-file-size=20GB
spring.servlet.multipart.max-request-size=20GB
upload.base-dir=${UPLOAD_BASE_DIR:/var/serverprovision/uploads}